services:
    - mysql
    - postgresql
    - mongodb
    - redis
    - memcached

before_install:
    - mysql -e "CREATE DATABASE test_database;" -uroot
    - mysql -e "CREATE USER 'test_user' IDENTIFIED BY 'test_password';" -uroot
    - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'test_user';" -uroot
    - psql -c "CREATE DATABASE test_database;" -U postgres
    - psql -c "CREATE USER test_user WITH PASSWORD 'test_password';" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE test_database to test_user;" -U postgres

language: erlang
otp_release:
    - 17.5
    - 18.2.1
    - 19.0

script: ./rebar3 ct
